Christophilus/Controllers/EntriesController.cs
namespace Christophilus.Controllers
{
    using System;
    using System.Web.Mvc;
    using System.Web.Routing;
    using Christophilus.Extensions;
    using Christophilus.Models;
    using Sparc.TagCloud;
    using Sparc.Mvc;
    using System.Linq;

    [Authorize]
    public class EntriesController : SparcBaseController
    {
        public string UserEmail 
        { 
            get { return System.Web.HttpContext.Current.User.Identity.Name; } 
        }

        public string UserId
        {
            get { return UserEmail.Sha1Hash(); }
        }
        
        public ActionResult Edit(DateTime? day)
        {
            if (!day.HasValue)
            {
                day = DateTime.Now;
            }

            var entry = JournalEntryService.GetEntry(UserId, day.Value) ??
                new JournalEntry(UserId, day.Value);

            return View(entry);
        }

        public ActionResult Index(int page = 0)
        {
            var entries = JournalEntryService.GetEntries(UserId, page);
            return View(entries);
        }

        public ActionResult TagCloud(DateTime start, DateTime end)
        {
            var phrases = JournalEntryService.GetEntries(UserId, start, end);
            var model = new TagCloudAnalyzer()
                .ComputeTagCloud(phrases)
                .Shuffle();
            return Json(new { tags = model });
        }

        [ValidateInput(false)]
        public ActionResult Update(JournalEntry entry)
        {
            entry.User = UserId;
            JournalEntryService.Save(entry);
            return Json(new { version = entry.Version.ToString() });
        }

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            ViewBag.UserEmail = UserEmail;
        }
    }
}

Christophilus/Views/Entries/Edit.cshtml
@model Christophilus.Models.JournalEntry

@{
    ViewBag.Title = "Edit " + Model.Day;
}

@DefineBlock("head").As(@<text>
    @MvcHtmlString.Create(Bundle.JavaScript()
        .Add("~/Scripts/Editor.js")
        .Add("~/Scripts/RemoteSaver.js")
        .Add("~/Scripts/LocalSaver.js")
        .Add("~/Scripts/SaverSync.js")
        .Render("~/Scripts/edit_#.js"))
</text>)

@DefineBlock("navigation").As(@<text>
    <a href="#" id="status">Saved</a> 
    <a href="@Url.Action("Index")" title="List"><img src="@Href("~/Content/img/list.png")" alt="List" /></a>
</text>)

<h1 class="editing-title">@Model.Day</h1>
<textarea rows="10" cols="10" id="editable-entry" version="@Model.Version" save-action="@Url.Action("Update", "Entries", new { day = Model.Day })" day="@Model.Day" class="entry-body autosize">@(new MvcHtmlString(Model.Body))</textarea>

Christophilus/Views/Entries/Index.cshtml
@model Christophilus.Models.PaginatedCollection<Christophilus.Models.JournalEntry>
@{
    ViewBag.Title = "Past Entries";
}

@DefineBlock("head").As(@<text>
    @MvcHtmlString.Create(Bundle.JavaScript()
        .Add("~/Scripts/index.js")
        .Render("~/Scripts/index_#.js"))
</text>)

@DefineBlock("navigation").As(@<a id="show-tagcloud" href="#tagcloud" title="Stats">
    <img src="@Href("~/Content/img/chart.png")" alt="Stats" /></a>)

<script type="text/html" id="tagCloud">
    <div class="tag-cloud">
        {{#tags}}
        <span class="tag kind-{{category}}">{{text}}</span>
        {{/tags}}
    </div>
</script>

<script type="text/html" id="tagCloudContainer">
    <div class="tag-cloud-container">
        <a class="close" href="#close"><img src="@Href("~/Content/img/close.png")" alt="[X]" /></a>
        
        <div class="cloud-types">
            last
            <a class="tag-360" href="?start=@DateTime.Now.AddDays(-365)&end=@DateTime.Now">365</a>
            <a class="tag-30"  href="?start=@DateTime.Now.AddDays(-30)&end=@DateTime.Now">30</a>
            <a class="tag-7 selected"  href="?start=@DateTime.Now.AddDays(-7)&end=@DateTime.Now">7</a>
            days
        </div>

        <h2 class="loading">Loading...</h2>
    </div>
</script>

<ul class="entries">
    @{
        var prevMoth = DateTime.MinValue;
    }
    @foreach (var entry in @Model.Values)
    {
        var date = DateTime.Parse(entry.Day);
        if (prevMoth.Month != date.Month || prevMoth.Year != date.Year)
        {
            prevMoth = date;
        <li class="month">@date.ToString("yyyy, MMM")</li>
        }
        <li><a href="@Url.Action("Edit", new { day = entry.Day })"><span class="day">@date.Day.Th()</span><span
            class="summary">@(new MvcHtmlString(entry.Summary))</span></a></li>
    }
</ul>

@if (@Model.ShowPagination)
{
    <ul class="pages">
        @if (@Model.HasPreviousPages)
        {
            <li><a href="@Url.Action("Index", new { page = Model.CurrentPage - 1 })">Prev</a></li>
        }
        @for (int pg = Model.FirstPageDisplay; pg <= Model.LastPageDisplay; ++pg)
        {
            <li class="@(pg == Model.CurrentPage ? "selected" : string.Empty)"><a href="@Url.Action("Index", new { page = pg })">@(pg + 1)</a></li>
        }
        @if (@Model.HasMorePages)
        {
            <li><a href="@Url.Action("Index", new { page = Model.CurrentPage + 1 })">Next</a></li>
        }
    </ul>
}